### ISSUE TITLE
Release version?

### ISSUE THREAD

**Issue by fmunteanu** [kaltura/nginx_mod_akamai_g2o#6]
Is it possible to have a release version, so I pack the module into Nginx RPM?

**Comment by erankor** [comment]
I don't quite understand what you mean, are you referring to a pre-compiled SO file of the module (to be loaded using the recently added nginx support for dynamic modules) ?

**Comment by erankor** [comment]
@jessp01 suggested that you are referring to a git tag... I created one now (v1.0) - 
https://github.com/kaltura/nginx_mod_akamai_g2o/releases/tag/v1.0

Thanks,

Eran

**Comment by fmunteanu** [comment]
@erankor I'm actually referring to Releases, not Tags. Is it possible to follow a standard versioning convention? For example:
https://github.com/maxmind/libmaxminddb/releases

For that project, I'm able to download the tarball and build an RPM package with it. Thank you for your support.

**Comment by erankor** [comment]
I removed the 'v' prefix, I thought we have it in our other nginx projects, but now saw that we don't...
The convention is now the same as it is in the other modules (e.g. nginx-vod-modules) - we normally use major.minor, but we may add another number if we release something that is very small.

**Comment by fmunteanu** [comment]
Thank you, this is very satisfactory.
